/**
 * Fixed interface chrome (nav labels, buttons, section eyebrows, form
 * labels, etc.) — everything that ISN'T pulled from portfolio.config.yaml.
 * Resolved once per page load from the same stored language as the CV
 * content, so the whole site is consistently one language, never mixed.
 */
import { getStoredLang } from '@/portfolio.config';

const STRINGS = {
  en: {
    common: {
      copyLink: 'Copy link',
      copied: 'Copied!',
    },
    nav: {
      about: 'About',
      stats: 'Stats',
      skills: 'Skills',
      languages: 'Languages',
      experience: 'Experience',
      projects: 'Projects',
      education: 'Education',
      certifications: 'Certifications',
      publications: 'Publications',
      testimonials: 'Testimonials',
      contact: 'Contact',
      more: 'More',
      blog: 'Blog',
      resume: 'Resume',
      downloadResume: 'Download Resume',
      viewResume: 'View Resume',
      shareAria: 'Share portfolio',
      themeAria: 'Toggle theme',
      langAria: 'Switch language',
      langTitleToEs: 'Ver en español',
      langTitleToEn: 'View in English',
      menuAria: 'Toggle menu',
    },
    hero: {
      openToOpportunities: 'Open to opportunities',
      viewWork: 'View My Work',
      viewResume: 'View Resume',
      scrollAria: 'Scroll down',
    },
    about: {
      eyebrow: 'About Me',
      heading: 'The person behind the keyboard.',
      languages: 'Languages',
    },
    skills: {
      eyebrow: 'Toolbox',
      heading: 'Skills & Technologies',
    },
    experience: {
      eyebrow: 'Career',
      heading: 'Work Experience',
    },
    projects: {
      eyebrow: 'From GitHub',
      heading: 'Recent Projects',
      repoAria: 'View repo on GitHub',
      liveAria: 'View live project',
      noDescription: 'No description yet.',
    },
    education: {
      eyebrow: 'Education',
      heading: 'Academic Background',
    },
    certifications: {
      eyebrow: 'Certifications',
      heading: 'Credentials & Badges',
      verify: 'Verify',
    },
    languages: {
      eyebrow: 'Communication',
      heading: 'Languages',
    },
    stats: {
      eyebrow: 'By the numbers',
      heading: 'At a Glance',
    },
    level: {
      native: 'Native',
      fluent: 'Fluent',
      conversational: 'Conversational',
      basic: 'Basic',
    },
    github: {
      eyebrow: 'Open source',
      heading: 'GitHub Activity',
      viewProfile: 'View profile',
      starsEarned: 'Stars earned',
      followers: 'Followers',
      publicRepos: 'Public repos',
      topLanguages: 'Top languages',
      rateLimited: 'GitHub API rate limit reached — stats will appear on next load.',
    },
    openToWork: {
      badge: 'Open to opportunities',
      subtitle: 'Available for full-time roles & freelance projects',
      cta: 'Get in touch',
      mailSubject: (name: string) => `Opportunity for ${name}`,
      dismissAria: 'Dismiss banner',
    },
    contact: {
      heading: 'Get In Touch',
      title: 'Let’s work\ntogether.',
      description:
        'Open to new opportunities. Whether you have a role in mind or just want to connect — my inbox is always open.',
      nameLabel: 'Your name',
      namePlaceholder: 'Your Name',
      emailLabel: 'Your email',
      emailPlaceholder: 'Your email',
      messageLabel: 'Message',
      messagePlaceholder: 'Tell me about your project or opportunity…',
      successMsg: 'Message sent! I’ll get back to you soon.',
      errorMsg: 'Something went wrong — please try emailing directly.',
      sending: 'Sending…',
      sendMessage: 'Send message',
      openEmailApp: 'Open in email app',
      mailtoHint: 'Opens your email client with the message pre-filled.',
      mailtoLink: 'Or email directly →',
      downloadResume: 'Download Resume',
      sharePortfolio: 'Share Portfolio',
      builtWith: 'Built with',
      forkIt: '— fork and make it yours.',
      whatsNew: "What's new in v1.3",
    },
    share: {
      title: 'Share your portfolio',
      portfolioLink: 'Portfolio link',
      copyLinkAria: 'Copy link',
      shareOn: 'Share on',
      email: 'Email',
      qrCode: 'QR code',
      qrHint: 'Put this on your business card, LinkedIn banner, or conference badge.',
      downloadPng: 'Download PNG',
      emailSignature: 'Email signature',
      copyHtml: 'Copy HTML',
      copied: 'Copied!',
      tweetText: 'Check out my portfolio 👋',
      emailSubject: (name: string) => `${name}'s Portfolio`,
      emailBody: (url: string) => `Hi,\n\nCheck out my portfolio:\n${url}`,
    },
    resumePage: {
      backToPortfolio: 'Portfolio',
      twoColumn: 'Two Column',
      classic: 'Classic',
      twoColumnAria: 'Two-column layout',
      classicAria: 'Classic layout',
      share: 'Share',
      shareAria: 'Share resume',
      savePdf: 'Save PDF',
      summary: 'Summary',
      experience: 'Experience',
      projects: 'Projects',
      skills: 'Skills',
      education: 'Education',
      certifications: 'Certifications',
      languages: 'Languages',
      publications: 'Publications',
    },
    chat: {
      greeting: (name: string) =>
        `Hi! I'm ${name}'s AI representative. Ask me anything about their experience, skills, or projects!`,
      title: 'AI Assistant',
      initializing: 'Initializing AI...',
      loadingModel: (pct: number) => `Loading model: ${pct}%`,
      finalizing: 'Finalizing setup...',
      unavailable: 'AI Unavailable',
      disclaimerLabel: 'Disclaimer:',
      disclaimerText:
        'AI-generated answers may contain errors. Please verify important information independently.',
      thinking: 'Thinking...',
      placeholderError: 'AI unavailable...',
      placeholderLoading: 'Loading AI model...',
      placeholderReady: (name: string) => `Ask about ${name}'s experience...`,
      errorPrefix: 'Sorry, I encountered an error:',
      unknownError: 'Unknown error',
    },
  },
  es: {
    common: {
      copyLink: 'Copiar enlace',
      copied: '¡Copiado!',
    },
    nav: {
      about: 'Acerca de',
      stats: 'Cifras',
      skills: 'Habilidades',
      languages: 'Idiomas',
      experience: 'Experiencia',
      projects: 'Proyectos',
      education: 'Educación',
      certifications: 'Certificaciones',
      publications: 'Publicaciones',
      testimonials: 'Testimonios',
      contact: 'Contacto',
      more: 'Más',
      blog: 'Blog',
      resume: 'CV',
      downloadResume: 'Descargar CV',
      viewResume: 'Ver CV',
      shareAria: 'Compartir portafolio',
      themeAria: 'Cambiar tema',
      langAria: 'Cambiar idioma',
      langTitleToEs: 'Ver en español',
      langTitleToEn: 'View in English',
      menuAria: 'Abrir menú',
    },
    hero: {
      openToOpportunities: 'Disponible para nuevas oportunidades',
      viewWork: 'Ver mi trabajo',
      viewResume: 'Ver CV',
      scrollAria: 'Bajar',
    },
    about: {
      eyebrow: 'Acerca de mí',
      heading: 'La persona detrás del teclado.',
      languages: 'Idiomas',
    },
    skills: {
      eyebrow: 'Caja de herramientas',
      heading: 'Habilidades y tecnologías',
    },
    experience: {
      eyebrow: 'Trayectoria',
      heading: 'Experiencia laboral',
    },
    projects: {
      eyebrow: 'Desde GitHub',
      heading: 'Proyectos recientes',
      repoAria: 'Ver repositorio en GitHub',
      liveAria: 'Ver proyecto en vivo',
      noDescription: 'Sin descripción todavía.',
    },
    education: {
      eyebrow: 'Educación',
      heading: 'Formación académica',
    },
    certifications: {
      eyebrow: 'Certificaciones',
      heading: 'Credenciales e insignias',
      verify: 'Verificar',
    },
    languages: {
      eyebrow: 'Comunicación',
      heading: 'Idiomas',
    },
    stats: {
      eyebrow: 'En números',
      heading: 'De un vistazo',
    },
    level: {
      native: 'Nativo',
      fluent: 'Fluido',
      conversational: 'Conversacional',
      basic: 'Básico',
    },
    github: {
      eyebrow: 'Código abierto',
      heading: 'Actividad en GitHub',
      viewProfile: 'Ver perfil',
      starsEarned: 'Estrellas obtenidas',
      followers: 'Seguidores',
      publicRepos: 'Repos públicos',
      topLanguages: 'Lenguajes principales',
      rateLimited: 'Se alcanzó el límite de la API de GitHub — las cifras aparecerán en la próxima carga.',
    },
    openToWork: {
      badge: 'Disponible para nuevas oportunidades',
      subtitle: 'Disponible para roles de tiempo completo y proyectos freelance',
      cta: 'Contáctame',
      mailSubject: (name: string) => `Oportunidad para ${name}`,
      dismissAria: 'Cerrar aviso',
    },
    contact: {
      heading: 'Contáctame',
      title: 'Trabajemos\njuntos.',
      description:
        'Disponible para nuevas oportunidades. Si tienes un puesto en mente o solo quieres conectar — mi bandeja de entrada siempre está abierta.',
      nameLabel: 'Tu nombre',
      namePlaceholder: 'Tu nombre',
      emailLabel: 'Tu correo',
      emailPlaceholder: 'Tu correo',
      messageLabel: 'Mensaje',
      messagePlaceholder: 'Cuéntame sobre tu proyecto u oportunidad…',
      successMsg: '¡Mensaje enviado! Te responderé pronto.',
      errorMsg: 'Algo salió mal — por favor intenta escribirme directo por correo.',
      sending: 'Enviando…',
      sendMessage: 'Enviar mensaje',
      openEmailApp: 'Abrir en app de correo',
      mailtoHint: 'Abre tu cliente de correo con el mensaje prellenado.',
      mailtoLink: 'O escribe directo →',
      downloadResume: 'Descargar CV',
      sharePortfolio: 'Compartir portafolio',
      builtWith: 'Hecho con',
      forkIt: '— haz tu propio fork.',
      whatsNew: 'Novedades en v1.3',
    },
    share: {
      title: 'Comparte tu portafolio',
      portfolioLink: 'Enlace del portafolio',
      copyLinkAria: 'Copiar enlace',
      shareOn: 'Compartir en',
      email: 'Correo',
      qrCode: 'Código QR',
      qrHint: 'Ponlo en tu tarjeta de presentación, banner de LinkedIn o gafete de conferencia.',
      downloadPng: 'Descargar PNG',
      emailSignature: 'Firma de correo',
      copyHtml: 'Copiar HTML',
      copied: '¡Copiado!',
      tweetText: 'Mira mi portafolio 👋',
      emailSubject: (name: string) => `Portafolio de ${name}`,
      emailBody: (url: string) => `Hola,\n\nMira mi portafolio:\n${url}`,
    },
    resumePage: {
      backToPortfolio: 'Portafolio',
      twoColumn: 'Dos columnas',
      classic: 'Clásico',
      twoColumnAria: 'Diseño de dos columnas',
      classicAria: 'Diseño clásico',
      share: 'Compartir',
      shareAria: 'Compartir CV',
      savePdf: 'Guardar PDF',
      summary: 'Resumen',
      experience: 'Experiencia',
      projects: 'Proyectos',
      skills: 'Habilidades',
      education: 'Educación',
      certifications: 'Certificaciones',
      languages: 'Idiomas',
      publications: 'Publicaciones',
    },
    chat: {
      greeting: (name: string) =>
        `¡Hola! Soy el representante de IA de ${name}. Pregúntame lo que quieras sobre su experiencia, habilidades o proyectos.`,
      title: 'Asistente IA',
      initializing: 'Iniciando IA...',
      loadingModel: (pct: number) => `Cargando modelo: ${pct}%`,
      finalizing: 'Terminando configuración...',
      unavailable: 'IA no disponible',
      disclaimerLabel: 'Aviso:',
      disclaimerText:
        'Las respuestas generadas por IA pueden contener errores. Por favor verifica la información importante de forma independiente.',
      thinking: 'Pensando...',
      placeholderError: 'IA no disponible...',
      placeholderLoading: 'Cargando modelo de IA...',
      placeholderReady: (name: string) => `Pregunta sobre la experiencia de ${name}...`,
      errorPrefix: 'Lo siento, ocurrió un error:',
      unknownError: 'Error desconocido',
    },
  },
} as const;

export const ui = STRINGS[getStoredLang()];

export function levelLabel(level: string): string {
  const key = level.toLowerCase() as keyof typeof ui.level;
  return ui.level[key] ?? level;
}
