/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.yaml  instead.
 *  Run   pnpm check-config  to validate before deploying.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from '@/lib/themes';
import rawConfigYaml from '../portfolio.config.yaml';

export type Lang = 'en' | 'es';
export const LANGUAGE_STORAGE_KEY = 'portfolio-lang';
export const DEFAULT_LANG: Lang = 'en';

interface LocalizedContent {
  title: string;
  tagline: string;
  about: string;
  stats: { label: string; value: number; prefix?: string; suffix?: string }[];
  languages: { name: string; level: string }[];
  skills: { category: string; items: string[] }[];
  experience: {
    company: string;
    role: string;
    period: string;
    description: string;
    highlights?: string[];
  }[];
  education: { institution: string; degree: string; period: string }[];
  certifications: {
    title: string;
    issuer: string;
    date: string;
    credentialUrl: string;
    badgeUrl: string;
    tags: string[];
  }[];
}

const rawConfig = rawConfigYaml as unknown as {
  name: string;
  email: string;
  phone?: string;
  location: string;
  avatarUrl: string;
  resumeUrl: string;
  resumeFileName: string;
  openToWork: boolean;
  defaultTheme: string;
  colorPreset: string;
  siteMode?: string;
  resumeTheme?: { twoColumn?: string; classic?: string };
  customColors?: PresetPalette;
  social: Record<string, string>;
  sections: { id: string; show: boolean }[];
  content: { en: LocalizedContent; es: LocalizedContent };
  projects: {
    name: string;
    description: string;
    tags: string[];
    liveUrl: string;
    repoUrl: string;
    featured: boolean;
  }[];
  publications: {
    title: string;
    authors: string;
    venue: string;
    year: string;
    url: string;
    type: string;
    tags: string[];
  }[];
  testimonials: {
    name: string;
    title: string;
    company: string;
    relationship: string;
    quote: string;
    photoUrl: string;
  }[];
  primaryColor?: string;
  siteUrl?: string;
  showPoweredBy?: boolean;
  contactFormEndpoint?: string;
  contactHeading?: string;
  contactTitle?: string;
  contactDescription?: string;
  analytics?: {
    goatcounterCode?: string;
  };
  blog?: {
    enabled?: boolean;
    title?: string;
    description?: string;
  };
};

// Resolved once per page load — the language toggle persists the choice and
// reloads the page rather than swapping content live. Keeps every section
// component reading plain config fields, unaware that content is bilingual.
export function getStoredLang(): Lang {
  if (typeof window === 'undefined') return DEFAULT_LANG;
  // ?lang=en|es (before the #) seeds the stored choice and is then removed
  // from the URL, so shared links open in a set language without pinning it
  const url = new URL(window.location.href);
  const fromUrl = url.searchParams.get('lang');
  if (fromUrl === 'en' || fromUrl === 'es') {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, fromUrl);
    url.searchParams.delete('lang');
    window.history.replaceState(null, '', url);
    return fromUrl;
  }
  const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return stored === 'en' || stored === 'es' ? stored : DEFAULT_LANG;
}

export function setStoredLang(lang: Lang) {
  window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  window.location.reload();
}

const currentLang = getStoredLang();
const localized = rawConfig.content[currentLang] ?? rawConfig.content.en;

// Mirror the resolved language on <html lang> — the static index.html always
// says "en", so assistive tech and SEO need this correction when es is active.
if (typeof document !== 'undefined') {
  document.documentElement.lang = currentLang;
}

export type SectionId =
  | 'about'
  | 'stats'
  | 'skills'
  | 'languages'
  | 'experience'
  | 'projects'
  | 'education'
  | 'certifications'
  | 'publications'
  | 'testimonials'
  | 'contact';

export interface SectionEntry {
  id: SectionId;
  show: boolean;
}

export interface Language {
  name: string;
  level: string;
}

export interface Certification {
  title: string;
  issuer: string;
  date: string;
  credentialUrl: string;
  badgeUrl: string;
  tags: string[];
}

export interface Stat {
  label: string;
  value: number;
  prefix?: string;
  suffix?: string;
}

export interface Publication {
  title: string;
  authors: string;
  venue: string;
  year: string;
  url: string;
  type: string;
  tags: string[];
}

export interface Testimonial {
  name: string;
  title: string;
  company: string;
  relationship: string;
  quote: string;
  photoUrl: string;
}

export interface ResumeTheme {
  twoColumn: ColorPreset;
  classic: ColorPreset;
}

export const config = {
  ...rawConfig,
  ...localized,
  lang: currentLang,
  colorPreset: rawConfig.colorPreset as ColorPreset,
  defaultTheme: rawConfig.defaultTheme as 'system' | 'light' | 'dark',
  siteMode: (rawConfig.siteMode ?? 'portfolio') as 'landing' | 'portfolio',
  sections: rawConfig.sections as SectionEntry[],
  stats: (localized.stats ?? []) as Stat[],
  languages: (localized.languages ?? []) as Language[],
  certifications: (localized.certifications ?? []) as Certification[],
  publications: (rawConfig.publications ?? []) as Publication[],
  testimonials: (rawConfig.testimonials ?? []) as Testimonial[],
  siteUrl: rawConfig.siteUrl ?? '',
  showPoweredBy: rawConfig.showPoweredBy ?? false,
  contactFormEndpoint: rawConfig.contactFormEndpoint ?? '',
  contactHeading: rawConfig.contactHeading ?? '',
  contactTitle: rawConfig.contactTitle ?? '',
  contactDescription: rawConfig.contactDescription ?? '',
  analytics: {
    goatcounterCode: rawConfig.analytics?.goatcounterCode ?? '',
  },
  blog: {
    enabled: rawConfig.blog?.enabled ?? false,
    title: rawConfig.blog?.title ?? 'Blog',
    description: rawConfig.blog?.description ?? '',
  },
  primaryColor: rawConfig.primaryColor ?? '',
  customColors: rawConfig.customColors,
  resumeTheme: {
    twoColumn: (rawConfig.resumeTheme?.twoColumn ??
      rawConfig.colorPreset) as ColorPreset,
    classic: (rawConfig.resumeTheme?.classic ??
      rawConfig.colorPreset) as ColorPreset,
  } as ResumeTheme,
};
